import type { Config } from 'tailwindcss'
import typography from '@tailwindcss/typography'

export default {
  content: ['./app/**/*.{ts,tsx}'],
  theme: {
    extend: {
      // All public board colours reference CSS variables
      // so the entire theme is driven by per-board token injection
      colors: {
        primary:    'var(--color-primary)',
        'primary-fg': 'var(--color-primary-fg)',
        accent:     'var(--color-accent)',
        'accent-fg':'var(--color-accent-fg)',
        background: 'var(--color-background)',
        surface:    'var(--color-surface)',
        'surface-subtle': 'var(--color-surface-subtle)',
        'text-primary':   'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted':     'var(--color-text-muted)',
        'text-inverse':   'var(--color-text-inverse)',
        border:           'var(--color-border)',
        'border-strong':  'var(--color-border-strong)',
        'border-inverse': 'var(--color-border-inverse)',
        'surface-inverse':'var(--color-surface-inverse)',
        'panel-strong':   'var(--color-panel-strong)',
        'panel-strong-fg':'var(--color-panel-strong-fg)',
        'badge-remote-bg':'var(--color-badge-remote-bg)',
        'badge-remote-fg':'var(--color-badge-remote-fg)',
        'badge-hybrid-bg':'var(--color-badge-hybrid-bg)',
        'badge-hybrid-fg':'var(--color-badge-hybrid-fg)',
        'badge-onsite-bg':'var(--color-badge-onsite-bg)',
        'badge-onsite-fg':'var(--color-badge-onsite-fg)',
        'badge-category-1-bg':'var(--color-badge-category-1-bg)',
        'badge-category-1-fg':'var(--color-badge-category-1-fg)',
        'badge-category-2-bg':'var(--color-badge-category-2-bg)',
        'badge-category-2-fg':'var(--color-badge-category-2-fg)',
        'badge-category-3-bg':'var(--color-badge-category-3-bg)',
        'badge-category-3-fg':'var(--color-badge-category-3-fg)',
        'badge-category-4-bg':'var(--color-badge-category-4-bg)',
        'badge-category-4-fg':'var(--color-badge-category-4-fg)',
        'badge-category-5-bg':'var(--color-badge-category-5-bg)',
        'badge-category-5-fg':'var(--color-badge-category-5-fg)',
        success:          'var(--color-success)',
        'success-bg':     'var(--color-success-bg)',
        warning:          'var(--color-warning)',
        'warning-bg':     'var(--color-warning-bg)',
        danger:           'var(--color-danger)',
        'danger-bg':      'var(--color-danger-bg)',
      },
      fontFamily: {
        display: 'var(--font-display)',
        body:    'var(--font-body)',
        mono:    'var(--font-mono)',
      },
      borderRadius: {
        sm:   'var(--radius-sm)',
        md:   'var(--radius-md)',
        lg:   'var(--radius-lg)',
        xl:   'var(--radius-xl)',
        '2xl':'var(--radius-2xl)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
    },
  },
  plugins: [typography],
} satisfies Config
